export const EmitEvents = {
    ALERT: "ALERT",
    REFETCH_CHATS: "REFETCH_CHATS",
    NEW_ATTACHMENT: "NEW_ATTACHMENT",
    NEW_MESSAGE_ALERT: "NEW_MESSAGE_ALERT",
    NEW_REQUEST: "NEW_REQUEST"
}


